// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_3_ef_core.models;

#nullable disable

namespace task_3_ef_core.Migrations
{
    [DbContext(typeof(mydatabase))]
    partial class mydatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepartmentClass1project", b =>
                {
                    b.Property<int>("departmentsID")
                        .HasColumnType("int");

                    b.Property<int>("projectsId")
                        .HasColumnType("int");

                    b.HasKey("departmentsID", "projectsId");

                    b.HasIndex("projectsId");

                    b.ToTable("DepartmentClass1project");
                });

            modelBuilder.Entity("task_3_ef_core.models.DepartmentClass1", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DepartmentClass1s");
                });

            modelBuilder.Entity("task_3_ef_core.models.addrsses", b =>
                {
                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.Property<string>("gov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeid");

                    b.ToTable("addrsses");
                });

            modelBuilder.Entity("task_3_ef_core.models.dep_pro", b =>
                {
                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentClass1id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("projectId", "DepartmentClass1id");

                    b.HasIndex("DepartmentClass1id");

                    b.ToTable("dep_pro");
                });

            modelBuilder.Entity("task_3_ef_core.models.employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATEDIFF(YEAR , [brithdate] , GETDATE() )");

                    b.Property<DateTime>("brithdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("bit");

                    b.Property<double>("salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(5000.0);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("task_3_ef_core.models.project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datatime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("DepartmentClass1project", b =>
                {
                    b.HasOne("task_3_ef_core.models.DepartmentClass1", null)
                        .WithMany()
                        .HasForeignKey("departmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_3_ef_core.models.project", null)
                        .WithMany()
                        .HasForeignKey("projectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_3_ef_core.models.addrsses", b =>
                {
                    b.HasOne("task_3_ef_core.models.employee", "employee")
                        .WithOne("addrsse")
                        .HasForeignKey("task_3_ef_core.models.addrsses", "employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("task_3_ef_core.models.dep_pro", b =>
                {
                    b.HasOne("task_3_ef_core.models.DepartmentClass1", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentClass1id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_3_ef_core.models.project", "project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("project");
                });

            modelBuilder.Entity("task_3_ef_core.models.employee", b =>
                {
                    b.HasOne("task_3_ef_core.models.DepartmentClass1", "Department")
                        .WithMany("employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("task_3_ef_core.models.DepartmentClass1", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("task_3_ef_core.models.employee", b =>
                {
                    b.Navigation("addrsse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
